/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseId = IDL.Nat;
export const Verdict = IDL.Record({
  'party2FaultPercentage' : IDL.Nat,
  'verdictStatement' : IDL.Text,
  'party1FaultPercentage' : IDL.Nat,
  'recommendedSolution' : IDL.Text,
  'party1Advice' : IDL.Vec(IDL.Text),
  'caseId' : CaseId,
  'party2Advice' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'analyzed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ConflictCase = IDL.Record({
  'id' : CaseId,
  'status' : CaseStatus,
  'title' : IDL.Text,
  'owner' : UserId,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'otherPartyDescription' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeCase' : IDL.Func([CaseId], [Verdict], []),
  'analyzeCaseAnonymous' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [Verdict],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserCases' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ConflictCase, IDL.Opt(Verdict)))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [CaseId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseId = IDL.Nat;
  const Verdict = IDL.Record({
    'party2FaultPercentage' : IDL.Nat,
    'verdictStatement' : IDL.Text,
    'party1FaultPercentage' : IDL.Nat,
    'recommendedSolution' : IDL.Text,
    'party1Advice' : IDL.Vec(IDL.Text),
    'caseId' : CaseId,
    'party2Advice' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'analyzed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ConflictCase = IDL.Record({
    'id' : CaseId,
    'status' : CaseStatus,
    'title' : IDL.Text,
    'owner' : UserId,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'otherPartyDescription' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeCase' : IDL.Func([CaseId], [Verdict], []),
    'analyzeCaseAnonymous' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Verdict],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserCases' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ConflictCase, IDL.Opt(Verdict)))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [CaseId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };