/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseId = bigint;
export type CaseStatus = { 'pending' : null } |
  { 'analyzed' : null };
export interface ConflictCase {
  'id' : CaseId,
  'status' : CaseStatus,
  'title' : string,
  'owner' : UserId,
  'description' : string,
  'timestamp' : bigint,
  'otherPartyDescription' : [] | [string],
}
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Verdict {
  'party2FaultPercentage' : bigint,
  'verdictStatement' : string,
  'party1FaultPercentage' : bigint,
  'recommendedSolution' : string,
  'party1Advice' : Array<string>,
  'caseId' : CaseId,
  'party2Advice' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeCase' : ActorMethod<[CaseId], Verdict>,
  'analyzeCaseAnonymous' : ActorMethod<[string, [] | [string]], Verdict>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserCases' : ActorMethod<[], Array<[ConflictCase, [] | [Verdict]]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCase' : ActorMethod<[string, string, [] | [string]], CaseId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];